<?php

namespace app\store\model;

use app\common\model\UploadGroup as UploadGroupModel;
use think\Session;

/**
 * 文件库分组模型
 * Class UploadGroup
 * @package app\store\model
 */
class UploadGroup extends UploadGroupModel
{
    public $admin_user;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        $this->admin_user =  Session::get('yoshop_store.user');
    }

    /**
     * 获取列表记录
     * @param string $group_type
     * @return false|\PDOStatement|string|\think\Collection
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function getList($group_type = 'image')
    {
        $where = compact('group_type');
        $where['store_shop_id'] = $this->admin_user['store_shop_id'];
        return $this->where($where)->order(['sort' => 'asc'])->select();
    }

    /**
     * 添加新记录
     * @param $data
     * @return false|int
     */
    public function add($data)
    {
        $data['wxapp_id'] = config('mini_weixin.wxapp_id');
        $data['store_shop_id'] = $this->admin_user['store_shop_id'];
        $data['sort'] = 100;
        return $this->save($data);
    }

    /**
     * 更新记录
     * @param $data
     * @return bool|int
     */
    public function edit($data)
    {
        return $this->allowField(true)->save($data) !== false;
    }

    /**
     * 删除记录
     * @return int
     */
    public function remove()
    {
        // 更新该分组下的所有文件
        $model = new UploadFile;
        $model->where(['group_id' => $this['group_id']])->update(['group_id' => 0]);
        return $this->delete();
    }

}
