<?php


namespace app\common\model\statements;


use app\common\model\BaseModel;
use think\Session;

class PointStatements extends BaseModel
{
    protected $name = 'point_statements';

    private $admin_user;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->admin_user = Session::get('yoshop_store.user');

    }

    public function record($data)
    {
        return $this->save($data);
    }

    public function getShopList()
    {
        $store_shop_id = $this->admin_user['store_shop_id'];
        return $this->where(['shop_id'=>$store_shop_id])
            ->order(['create_time' => 'desc'])
            ->paginate(15, false, [
                'query' => \request()->request()
            ]);
    }

    public function getList()
    {
        return $this
            ->order(['create_time' => 'desc'])
            ->paginate(15, false, [
                'query' => \request()->request()
            ]);
    }
}